[package]
name = "levelspecter"
version = "0.9.0"
authors = ["jgerber"]
edition = "2018"

[dependencies]
nom="5.0.0"
aschar-casesensitive = { git = "https://github.com/jlgerber/aschar-casesensitive.git" }
failure = "0.1.5"

[features]
default = []
case-insensitive = []   
