[package]
name = "levelspecter"
version = "0.1.0"
authors = ["jgerber"]
edition = "2018"

[dependencies]
nom="5.0.0-beta2"
aschar-casesensitive = { git = "https://github.com/jlgerber/aschar-casesensitive.git" }
